import type { Email, PurchaseOrder } from '../../../types/types.js';

export const fakePO1: PurchaseOrder = {
  po_id: 'PO-1',
  buyer: {
    buyer_id: 'B-1',
    company_name: 'Buyer Co',
    registration_no: 123,
    vat_no: 'VAT-1',
    billing_address: '123 Main St',
    billing_city: 'City',
    billing_country: 'Country',
    billing_postcode: 12345,
    contact_name: 'Alice',
    contact_email: 'alice@buyer.com',
    contact_phone: '+100000',
    default_currency: 'EUR',
    default_incoterms: 'DAP',
    default_payment_terms: 'Net 30',
  },
  supplier: {
    supplier_id: 'S-1',
    supplier_name: 'Supplier Ltd',
    tax_id: 'TAX-1',
    vat_no: 'VAT-S1',
    address_line1: '1 Supply Ave',
    city: 'Supplytown',
    country: 'Suppcountry',
    postcode: 5555,
    contact_name: 'Bob',
    contact_email: 'bob@supplier.com',
    contact_phone: '+200000',
    payment_terms: 'Net 15',
    currency: 'USD',
    incoterms_preference: 'FCA',
    lead_time_days: 10,
    preferred_ship_method: 'Air',
    rating: 5,
  },
  issue_date: '2025-01-01',
  confirm_target_date: '2025-01-03',
  expected_ship_date: '2025-01-10',
  expected_delivery_date: '2025-01-15',
  currency: 'EUR',
  incoterms: 'DAP',
  payment_terms: 'Net 30',
  ship_method: 'Air',
  ship_from_country: 'Suppcountry',
  ship_to_city: 'City',
  ship_to_country: 'Country',
  freight_terms: 'Prepaid',
  carrier: 'FastCarrier',
  total_lines: 1,
  subtotal: 100,
  tax_total: 10,
  freight_cost: 5,
  grand_total: 115,
  status: 'OPEN',
  notes: '',
  lines: {
    po_id: 'PO-1',
    line_no: 1,
    sku: 'SKU-1',
    description: 'Super Widget XL',
    category: 'Widgets',
    qty: 12,
    uom: 'EA',
    unit_price: 5,
    discount_pct: 0,
    net_unit_price: 5,
    currency: 'EUR',
    tax_rate: 0.2,
    net_amount: 60,
    tax_amount: 12,
    total_amount: 72,
    country_of_origin: 'Suppcountry',
    need_by_date: '2025-01-15',
  },
};

export const fakePO2: PurchaseOrder = {
  po_id: 'PO-2',
  buyer: {
    buyer_id: 'B-2',
    company_name: 'Acme Corp',
    registration_no: 234,
    vat_no: 'VAT-2',
    billing_address: '456 Side Rd',
    billing_city: 'Townsville',
    billing_country: 'Otherland',
    billing_postcode: 54321,
    contact_name: 'Carol',
    contact_email: 'carol@acme.com',
    contact_phone: '+111111',
    default_currency: 'USD',
    default_incoterms: 'CIF',
    default_payment_terms: 'Net 45',
  },
  supplier: {
    supplier_id: 'S-2',
    supplier_name: 'Gizmo Inc',
    tax_id: 'TAX-2',
    vat_no: 'VAT-S2',
    address_line1: '99 Tech Blvd',
    city: 'Techville',
    country: 'Techland',
    postcode: 9876,
    contact_name: 'Dave',
    contact_email: 'dave@gizmo.com',
    contact_phone: '+222222',
    payment_terms: 'Net 20',
    currency: 'EUR',
    incoterms_preference: 'EXW',
    lead_time_days: 14,
    preferred_ship_method: 'Road',
    rating: 4,
  },
  issue_date: '2025-02-02',
  confirm_target_date: '2025-02-05',
  expected_ship_date: '2025-02-15',
  expected_delivery_date: '2025-02-21',
  currency: 'USD',
  incoterms: 'CIF',
  payment_terms: 'Net 45',
  ship_method: 'Road',
  ship_from_country: 'Techland',
  ship_to_city: 'Townsville',
  ship_to_country: 'Otherland',
  freight_terms: 'Collect',
  carrier: 'RoadRunner',
  total_lines: 2,
  subtotal: 200,
  tax_total: 20,
  freight_cost: 10,
  grand_total: 230,
  status: 'OPEN',
  notes: '',
  lines: {
    po_id: 'PO-2',
    line_no: 1,
    sku: 'SKU-2',
    description: 'Gizmo Pro 3000',
    category: 'Gizmos',
    qty: 8,
    uom: 'EA',
    unit_price: 15,
    discount_pct: 5,
    net_unit_price: 14.25,
    currency: 'USD',
    tax_rate: 0.15,
    net_amount: 114,
    tax_amount: 17.1,
    total_amount: 131.1,
    country_of_origin: 'Techland',
    need_by_date: '2025-02-21',
  },
};

export const fakeEmail1: Email = {
  sent: '2025-01-02T10:00:00Z',
  received: '2025-01-02T10:05:00Z',
  from_: 'alice@buyer.com',
  to: ['bob@supplier.com'],
  cc: [],
  subject: 'Shipment of 12 Super Widget XL',
  body: 'Hello Bob, confirming shipment for 12 Super Widget XL as per our order. Regards, Alice',
  thread_id: 1,
};

export const fakeEmail2: Email = {
  sent: '2025-02-10T08:30:00Z',
  received: '2025-02-10T08:31:00Z',
  from_: 'carol@acme.com',
  to: ['dave@gizmo.com'],
  cc: [],
  subject: 'About Gizmo Pro 3000 delivery',
  body: 'Hi Dave, please update us about the 8 Gizmo Pro 3000 units for PO-2. Thanks, Carol',
  thread_id: 2,
};

export const fakeSpamEmail = {
  sent: '2025-03-01T12:00:00Z',
  received: '2025-03-01T12:00:01Z',
  from_: 'newsletter@randomsite.com',
  to: ['user@company.com'],
  cc: [],
  subject: 'Special offer just for you!',
  body: 'Buy one get one free, limited time!',
  thread_id: 99,
};
